# A simplified blueprint for a single web service
services:
  - type: web
    name: cache-visualizer # You can name this whatever you like
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    healthCheckPath: /