# This is a Render Blueprint file.
# It tells Render how to deploy your project's frontend and backend.
# https://render.com/docs/blueprint-spec

services:
  # 1. The Python Backend (Web Service)
  - type: web
    name: lru-cache-api # A name for your backend service
    env: python
    rootDir: Backend # Tells Render to look inside the "Backend" folder
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    healthCheckPath: / # Optional: Render can check if your app is running

  # 2. The HTML/CSS/JS Frontend (Static Site)
  - type: static
    name: lru-cache-visualizer # A name for your frontend service
    rootDir: frontend # Tells Render to look inside the "frontend" folder
    # No build command is needed for a simple HTML site
    # Render will automatically serve the index.html file
    # This rewrite rule is important for single-page apps, good practice to have.
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
